<a href="https://colab.research.google.com/github/Arinjay-04/DSBDL-LAB/blob/main/Assignment7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!pip install pdfplumber
import pdfplumber
import pandas as pd
from pdfplumber.utils import extract_text, get_bbox_overlap, obj_to_bbox
import tabulate



In [ ]:
def extract_text_from_pdf(path_to_pdf):
  all_text = []
  with pdfplumber.open(path_to_pdf) as pdf:
    for page_number, page in enumerate(pdf.pages, start=1):
      page_text = page.extract_text()
      if page_text:
                all_text.append(page_text)
      else:
          print(f"Warning: No text found on page {page_number}.")
  return "\n".join(all_text)


In [ ]:
pdf_path = r"/content/testdoc.pdf"
extracted_text = extract_text_from_pdf(pdf_path)
print(extracted_text)

Millions of people in India took part in an annual tree planting drive Sunday. More than 250 million
saplings were planted in a single day across the country's most-populous state.
The campaign was led by Uttar Pradesh state government officials, lawmakers, and activists, in a
bid to reduce carbon emissions and combat climate change.
Where were the trees planted?
The saplings were planted by volunteers in forests, farms, schools, and along riverbanks and
highways.
"We are committed to increasing the forest cover of Uttar Pradesh to over 15% of the total land area
in the next five years,'' said state forest official Manoj Singh.
According to another government official, the forest cover of the state has increased over the last
few years.
"There has been an increase of 127 sqare kilometers [79 sqare miles] in the forest cover in Uttar
Pradesh as compared to 2017," a state government spokesperson was quoted as saying in The
Indian Express newspaper.
"There has also been an increase in tre

In [ ]:
! pip install nltk

In [ ]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_r

True

In [ ]:
from nltk import word_tokenize, sent_tokenize
print(word_tokenize(extracted_text))
words = word_tokenize(extracted_text)


['Millions', 'of', 'people', 'in', 'India', 'took', 'part', 'in', 'an', 'annual', 'tree', 'planting', 'drive', 'Sunday', '.', 'More', 'than', '250', 'million', 'saplings', 'were', 'planted', 'in', 'a', 'single', 'day', 'across', 'the', 'country', "'s", 'most-populous', 'state', '.', 'The', 'campaign', 'was', 'led', 'by', 'Uttar', 'Pradesh', 'state', 'government', 'officials', ',', 'lawmakers', ',', 'and', 'activists', ',', 'in', 'a', 'bid', 'to', 'reduce', 'carbon', 'emissions', 'and', 'combat', 'climate', 'change', '.', 'Where', 'were', 'the', 'trees', 'planted', '?', 'The', 'saplings', 'were', 'planted', 'by', 'volunteers', 'in', 'forests', ',', 'farms', ',', 'schools', ',', 'and', 'along', 'riverbanks', 'and', 'highways', '.', '``', 'We', 'are', 'committed', 'to', 'increasing', 'the', 'forest', 'cover', 'of', 'Uttar', 'Pradesh', 'to', 'over', '15', '%', 'of', 'the', 'total', 'land', 'area', 'in', 'the', 'next', 'five', 'years', ',', "''", 'said', 'state', 'forest', 'official', 'Mano

In [ ]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word.lower() not in stop_words]
print(filtered_words)

['Millions', 'people', 'India', 'took', 'part', 'annual', 'tree', 'planting', 'drive', 'Sunday', '.', '250', 'million', 'saplings', 'planted', 'single', 'day', 'across', 'country', "'s", 'most-populous', 'state', '.', 'campaign', 'led', 'Uttar', 'Pradesh', 'state', 'government', 'officials', ',', 'lawmakers', ',', 'activists', ',', 'bid', 'reduce', 'carbon', 'emissions', 'combat', 'climate', 'change', '.', 'trees', 'planted', '?', 'saplings', 'planted', 'volunteers', 'forests', ',', 'farms', ',', 'schools', ',', 'along', 'riverbanks', 'highways', '.', '``', 'committed', 'increasing', 'forest', 'cover', 'Uttar', 'Pradesh', '15', '%', 'total', 'land', 'area', 'next', 'five', 'years', ',', "''", 'said', 'state', 'forest', 'official', 'Manoj', 'Singh', '.', 'According', 'another', 'government', 'official', ',', 'forest', 'cover', 'state', 'increased', 'last', 'years', '.', '``', 'increase', '127', 'sqare', 'kilometers', '[', '79', 'sqare', 'miles', ']', 'forest', 'cover', 'Uttar', 'Pradesh

In [ ]:
from nltk.stem.snowball import SnowballStemmer
porter = SnowballStemmer(language='english')
stemmed_words = [porter.stem(word) for word in filtered_words]
print(stemmed_words)


['million', 'peopl', 'india', 'took', 'part', 'annual', 'tree', 'plant', 'drive', 'sunday', '.', '250', 'million', 'sapl', 'plant', 'singl', 'day', 'across', 'countri', "'s", 'most-popul', 'state', '.', 'campaign', 'led', 'uttar', 'pradesh', 'state', 'govern', 'offici', ',', 'lawmak', ',', 'activist', ',', 'bid', 'reduc', 'carbon', 'emiss', 'combat', 'climat', 'chang', '.', 'tree', 'plant', '?', 'sapl', 'plant', 'volunt', 'forest', ',', 'farm', ',', 'school', ',', 'along', 'riverbank', 'highway', '.', '``', 'commit', 'increas', 'forest', 'cover', 'uttar', 'pradesh', '15', '%', 'total', 'land', 'area', 'next', 'five', 'year', ',', "''", 'said', 'state', 'forest', 'offici', 'manoj', 'singh', '.', 'accord', 'anoth', 'govern', 'offici', ',', 'forest', 'cover', 'state', 'increas', 'last', 'year', '.', '``', 'increas', '127', 'sqare', 'kilomet', '[', '79', 'sqare', 'mile', ']', 'forest', 'cover', 'uttar', 'pradesh', 'compar', '2017', ',', "''", 'state', 'govern', 'spokesperson', 'quot', 'say

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmed_words = [lemmatizer.lemmatize(word, 'v') for word in filtered_words]
print(lemmed_words)

['Millions', 'people', 'India', 'take', 'part', 'annual', 'tree', 'plant', 'drive', 'Sunday', '.', '250', 'million', 'saplings', 'plant', 'single', 'day', 'across', 'country', "'s", 'most-populous', 'state', '.', 'campaign', 'lead', 'Uttar', 'Pradesh', 'state', 'government', 'officials', ',', 'lawmakers', ',', 'activists', ',', 'bid', 'reduce', 'carbon', 'emissions', 'combat', 'climate', 'change', '.', 'tree', 'plant', '?', 'saplings', 'plant', 'volunteer', 'forest', ',', 'farm', ',', 'school', ',', 'along', 'riverbanks', 'highways', '.', '``', 'commit', 'increase', 'forest', 'cover', 'Uttar', 'Pradesh', '15', '%', 'total', 'land', 'area', 'next', 'five', 'years', ',', "''", 'say', 'state', 'forest', 'official', 'Manoj', 'Singh', '.', 'According', 'another', 'government', 'official', ',', 'forest', 'cover', 'state', 'increase', 'last', 'years', '.', '``', 'increase', '127', 'sqare', 'kilometers', '[', '79', 'sqare', 'miles', ']', 'forest', 'cover', 'Uttar', 'Pradesh', 'compare', '2017'

In [ ]:
from nltk import pos_tag
tags = tokens_tag = pos_tag(words)
tags

[('Millions', 'NNS'),
 ('of', 'IN'),
 ('people', 'NNS'),
 ('in', 'IN'),
 ('India', 'NNP'),
 ('took', 'VBD'),
 ('part', 'NN'),
 ('in', 'IN'),
 ('an', 'DT'),
 ('annual', 'JJ'),
 ('tree', 'NN'),
 ('planting', 'VBG'),
 ('drive', 'JJ'),
 ('Sunday', 'NNP'),
 ('.', '.'),
 ('More', 'JJR'),
 ('than', 'IN'),
 ('250', 'CD'),
 ('million', 'CD'),
 ('saplings', 'NNS'),
 ('were', 'VBD'),
 ('planted', 'VBN'),
 ('in', 'IN'),
 ('a', 'DT'),
 ('single', 'JJ'),
 ('day', 'NN'),
 ('across', 'IN'),
 ('the', 'DT'),
 ('country', 'NN'),
 ("'s", 'POS'),
 ('most-populous', 'JJ'),
 ('state', 'NN'),
 ('.', '.'),
 ('The', 'DT'),
 ('campaign', 'NN'),
 ('was', 'VBD'),
 ('led', 'VBN'),
 ('by', 'IN'),
 ('Uttar', 'NNP'),
 ('Pradesh', 'NNP'),
 ('state', 'NN'),
 ('government', 'NN'),
 ('officials', 'NNS'),
 (',', ','),
 ('lawmakers', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('activists', 'NNS'),
 (',', ','),
 ('in', 'IN'),
 ('a', 'DT'),
 ('bid', 'NN'),
 ('to', 'TO'),
 ('reduce', 'VB'),
 ('carbon', 'NN'),
 ('emissions', 'NNS'),

In [ ]:
from collections import Counter
freq = Counter(words)
freq

Counter({'Millions': 1,
         'of': 14,
         'people': 1,
         'in': 11,
         'India': 4,
         'took': 1,
         'part': 1,
         'an': 3,
         'annual': 2,
         'tree': 4,
         'planting': 2,
         'drive': 2,
         'Sunday': 1,
         '.': 18,
         'More': 1,
         'than': 1,
         '250': 1,
         'million': 2,
         'saplings': 8,
         'were': 3,
         'planted': 4,
         'a': 7,
         'single': 1,
         'day': 1,
         'across': 2,
         'the': 24,
         'country': 2,
         "'s": 2,
         'most-populous': 1,
         'state': 5,
         'The': 7,
         'campaign': 1,
         'was': 2,
         'led': 1,
         'by': 3,
         'Uttar': 4,
         'Pradesh': 4,
         'government': 4,
         'officials': 2,
         ',': 20,
         'lawmakers': 1,
         'and': 8,
         'activists': 1,
         'bid': 1,
         'to': 10,
         'reduce': 1,
         'carbon': 1,
       

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np



In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(words)
dense_matrix = tfidf_matrix.todense()
dense_array = np.array(dense_matrix)
words = tfidf_vectorizer.get_feature_names_out()
print("TF-IDF Matrix:")
print(dense_array)

print("\nFeature Names (Words):")
print(words)

TF-IDF Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Feature Names (Words):
['05' '127' '15' '2017' '2019' '2030' '250' '60' '79' '80' '89' '95'
 'about' 'according' 'across' 'activists' 'adding' 'all' 'allocated'
 'along' 'also' 'an' 'and' 'annual' 'another' 'are' 'area' 'as'
 'ascertain' 'average' 'been' 'being' 'besides' 'bid' 'billion' 'by'
 'campaign' 'can' 'carbon' 'carried' 'carry' 'change' 'chauhan' 'citing'
 'climate' 'codes' 'combat' 'committed' 'compared' 'concern' 'country'
 'cover' 'dara' 'day' 'development' 'disease' 'drive' 'drives' 'emissions'
 'exactly' 'express' 'extent' 'farms' 'few' 'five' 'for' 'forest'
 'forests' 'formed' 'four' 'further' 'geo' 'government' 'growing'
 'happened' 'has' 'have' 'he' 'hectares' 'highways' 'how' 'however' 'in'
 'increase' 'increased' 'increasing' 'india' 'indian' 'industrial' 'is'
 'its' 'kilometers' 'lack' 'land' 'las

In [ ]:
for i, doc in enumerate(words):
    print(f"\nDocument {i+1}: {doc}")
    word_scores = [(word, dense_array[i][j]) for j, word in enumerate(words)]


    word_scores.sort(key=lambda x: x[1], reverse=True)

    for word, score in word_scores:
        print(f"{word}: {score:.4f}")

Streaming output truncated to the last 5000 lines.
sunday: 0.0000
survey: 0.0000
survival: 0.0000
survive: 0.0000
survived: 0.0000
tagged: 0.0000
teams: 0.0000
term: 0.0000
than: 0.0000
that: 0.0000
the: 0.0000
there: 0.0000
these: 0.0000
third: 0.0000
to: 0.0000
told: 0.0000
took: 0.0000
total: 0.0000
tree: 0.0000
trees: 0.0000
under: 0.0000
usually: 0.0000
uttar: 0.0000
verify: 0.0000
volunteers: 0.0000
vowed: 0.0000
was: 0.0000
water: 0.0000
we: 0.0000
were: 0.0000
what: 0.0000
where: 0.0000
whether: 0.0000
years: 0.0000

Document 164: than
as: 1.0000
05: 0.0000
127: 0.0000
15: 0.0000
2017: 0.0000
2019: 0.0000
2030: 0.0000
250: 0.0000
60: 0.0000
79: 0.0000
80: 0.0000
89: 0.0000
95: 0.0000
about: 0.0000
according: 0.0000
across: 0.0000
activists: 0.0000
adding: 0.0000
all: 0.0000
allocated: 0.0000
along: 0.0000
also: 0.0000
an: 0.0000
and: 0.0000
annual: 0.0000
another: 0.0000
are: 0.0000
area: 0.0000
ascertain: 0.0000
average: 0.0000
been: 0.0000
being: 0.0000
besides: 0.0000
bid: 0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()


result = tfidf.fit_transform(words)


print('\nidf values:')

idf_values = list(zip(tfidf.get_feature_names_out(), tfidf.idf_))


idf_values.sort(key=lambda x: x[1], reverse=True)


for word, idf in idf_values:
    print(word, ':', idf)




print('\nWord indexes:')
print(tfidf.vocabulary_)


print('\ntf-idf value:')
print(result)

print('\ntf-idf values in matrix form:')
print(result.toarray())


idf values:
05 : 5.553876891600541
127 : 5.553876891600541
15 : 5.553876891600541
2017 : 5.553876891600541
2019 : 5.553876891600541
2030 : 5.553876891600541
250 : 5.553876891600541
60 : 5.553876891600541
79 : 5.553876891600541
80 : 5.553876891600541
89 : 5.553876891600541
95 : 5.553876891600541
about : 5.553876891600541
according : 5.553876891600541
across : 5.553876891600541
activists : 5.553876891600541
adding : 5.553876891600541
all : 5.553876891600541
allocated : 5.553876891600541
along : 5.553876891600541
also : 5.553876891600541
an : 5.553876891600541
and : 5.553876891600541
annual : 5.553876891600541
another : 5.553876891600541
are : 5.553876891600541
area : 5.553876891600541
as : 5.553876891600541
ascertain : 5.553876891600541
average : 5.553876891600541
been : 5.553876891600541
being : 5.553876891600541
besides : 5.553876891600541
bid : 5.553876891600541
billion : 5.553876891600541
by : 5.553876891600541
campaign : 5.553876891600541
can : 5.553876891600541
carbon : 5.55387689